<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/test/', 'middleware' => 'admin','as'=>'admin.test.'), function () {

Route::get('tests', ['as'=> 'tests.index', 'uses' => 'Test\TestController@index']);
Route::post('tests', ['as'=> 'tests.store', 'uses' => 'Test\TestController@store']);
Route::get('tests/create', ['as'=> 'tests.create', 'uses' => 'Test\TestController@create']);
Route::put('tests/{tests}', ['as'=> 'tests.update', 'uses' => 'Test\TestController@update']);
Route::patch('tests/{tests}', ['as'=> 'tests.update', 'uses' => 'Test\TestController@update']);
Route::get('tests/{id}/delete', array('as' => 'tests.delete', 'uses' => 'Test\TestController@getDelete'));
Route::get('tests/{id}/confirm-delete', array('as' => 'tests.confirm-delete', 'uses' => 'Test\TestController@getModalDelete'));
Route::get('tests/{tests}', ['as'=> 'tests.show', 'uses' => 'Test\TestController@show']);
Route::get('tests/{tests}/edit', ['as'=> 'tests.edit', 'uses' => 'Test\TestController@edit']);

});
